- name: "README Accuracy"
  trigger: "src/**/*"
  safety: "README.md"
  instructions: |
    Source code in src/ has been modified. Please review README.md for accuracy:
    1. Verify project overview still reflects current functionality
    2. Check that usage examples are still correct
    3. Ensure installation/setup instructions remain valid
    4. Update any sections that reference changed code

- name: "Architecture Documentation Accuracy"
  trigger: "src/**/*"
  safety: "doc/architecture.md"
  instructions: |
    Source code in src/ has been modified. Please review doc/architecture.md for accuracy:
    1. Verify the documented architecture matches the current implementation
    2. Check that file paths and directory structures are still correct
    3. Ensure component descriptions reflect actual behavior
    4. Update any diagrams or flows that may have changed
