# yaml-language-server: $schema=src/deepwork/schemas/policy.schema.json
- name: "README Accuracy"
  trigger: "src/**/*"
  safety: "README.md"
  instructions: |
    Source code in src/ has been modified. Please review README.md for accuracy:
    1. Verify project overview still reflects current functionality
    2. Check that usage examples are still correct
    3. Ensure installation/setup instructions remain valid
    4. Update any sections that reference changed code

- name: "Architecture Documentation Accuracy"
  trigger: "src/**/*"
  safety: "doc/architecture.md"
  instructions: |
    Source code in src/ has been modified. Please review doc/architecture.md for accuracy:
    1. Verify the documented architecture matches the current implementation
    2. Check that file paths and directory structures are still correct
    3. Ensure component descriptions reflect actual behavior
    4. Update any diagrams or flows that may have changed

- name: "Standard Jobs Source of Truth"
  trigger:
    - ".deepwork/jobs/deepwork_jobs/**/*"
    - ".deepwork/jobs/deepwork_policy/**/*"
  safety:
    - "src/deepwork/standard_jobs/deepwork_jobs/**/*"
    - "src/deepwork/standard_jobs/deepwork_policy/**/*"
  instructions: |
    You modified files in `.deepwork/jobs/deepwork_jobs/` or `.deepwork/jobs/deepwork_policy/`.

    **These are installed copies, NOT the source of truth!**

    Standard jobs (deepwork_jobs, deepwork_policy) must be edited in their source location:
    - Source: `src/deepwork/standard_jobs/[job_name]/`
    - Installed copy: `.deepwork/jobs/[job_name]/` (DO NOT edit directly)

    **Required action:**
    1. Revert your changes to `.deepwork/jobs/deepwork_*/`
    2. Make the same changes in `src/deepwork/standard_jobs/[job_name]/`
    3. Run `deepwork install --platform claude` to sync changes
    4. Verify the changes propagated correctly

    See CLAUDE.md section "CRITICAL: Editing Standard Jobs" for details.

- name: "Version and Changelog Update"
  trigger: "src/**/*"
  safety:
    - "pyproject.toml"
    - "CHANGELOG.md"
  instructions: |
    Source code in src/ has been modified. **You MUST evaluate whether version and changelog updates are needed.**

    **Evaluate the changes:**
    1. Is this a bug fix, new feature, breaking change, or internal refactor?
    2. Does this change affect the public API or user-facing behavior?
    3. Would users need to know about this change when upgrading?

    **If version update is needed:**
    1. Update the `version` field in `pyproject.toml` following semantic versioning:
       - PATCH (0.1.x): Bug fixes, minor internal changes
       - MINOR (0.x.0): New features, non-breaking changes
       - MAJOR (x.0.0): Breaking changes
    2. Add an entry to `CHANGELOG.md` under an appropriate version header:
       - Use categories: Added, Changed, Fixed, Removed, Deprecated, Security
       - Include a clear, user-facing description of what changed
       - Follow the Keep a Changelog format

    **If NO version update is needed** (e.g., tests only, comments, internal refactoring with no behavior change):
    - Explicitly state why no version bump is required

    **This policy requires explicit action** - either update both files or justify why no update is needed.